// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: rental.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rental struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarId         int64                  `protobuf:"varint,3,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,6,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rental) Reset() {
	*x = Rental{}
	mi := &file_rental_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rental) ProtoMessage() {}

func (x *Rental) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rental.ProtoReflect.Descriptor instead.
func (*Rental) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{0}
}

func (x *Rental) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rental) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Rental) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *Rental) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Rental) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Rental) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *Rental) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RentCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarId         int64                  `protobuf:"varint,2,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	DailyPrice    float64                `protobuf:"fixed64,5,opt,name=daily_price,json=dailyPrice,proto3" json:"daily_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentCarRequest) Reset() {
	*x = RentCarRequest{}
	mi := &file_rental_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentCarRequest) ProtoMessage() {}

func (x *RentCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentCarRequest.ProtoReflect.Descriptor instead.
func (*RentCarRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{1}
}

func (x *RentCarRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RentCarRequest) GetCarId() int64 {
	if x != nil {
		return x.CarId
	}
	return 0
}

func (x *RentCarRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *RentCarRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *RentCarRequest) GetDailyPrice() float64 {
	if x != nil {
		return x.DailyPrice
	}
	return 0
}

type RentCarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      int64                  `protobuf:"varint,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RentCarResponse) Reset() {
	*x = RentCarResponse{}
	mi := &file_rental_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RentCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RentCarResponse) ProtoMessage() {}

func (x *RentCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RentCarResponse.ProtoReflect.Descriptor instead.
func (*RentCarResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{2}
}

func (x *RentCarResponse) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

type CompleteRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      int64                  `protobuf:"varint,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRentalRequest) Reset() {
	*x = CompleteRentalRequest{}
	mi := &file_rental_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRentalRequest) ProtoMessage() {}

func (x *CompleteRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRentalRequest.ProtoReflect.Descriptor instead.
func (*CompleteRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRentalRequest) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

type CompleteRentalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRentalResponse) Reset() {
	*x = CompleteRentalResponse{}
	mi := &file_rental_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRentalResponse) ProtoMessage() {}

func (x *CompleteRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRentalResponse.ProtoReflect.Descriptor instead.
func (*CompleteRentalResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteRentalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      int64                  `protobuf:"varint,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalRequest) Reset() {
	*x = GetRentalRequest{}
	mi := &file_rental_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalRequest) ProtoMessage() {}

func (x *GetRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalRequest.ProtoReflect.Descriptor instead.
func (*GetRentalRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{5}
}

func (x *GetRentalRequest) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

type GetRentalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rental        *Rental                `protobuf:"bytes,1,opt,name=rental,proto3" json:"rental,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRentalResponse) Reset() {
	*x = GetRentalResponse{}
	mi := &file_rental_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRentalResponse) ProtoMessage() {}

func (x *GetRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRentalResponse.ProtoReflect.Descriptor instead.
func (*GetRentalResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{6}
}

func (x *GetRentalResponse) GetRental() *Rental {
	if x != nil {
		return x.Rental
	}
	return nil
}

type ListUserRentalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRentalsRequest) Reset() {
	*x = ListUserRentalsRequest{}
	mi := &file_rental_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRentalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRentalsRequest) ProtoMessage() {}

func (x *ListUserRentalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRentalsRequest.ProtoReflect.Descriptor instead.
func (*ListUserRentalsRequest) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserRentalsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListUserRentalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rentals       []*Rental              `protobuf:"bytes,1,rep,name=rentals,proto3" json:"rentals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRentalsResponse) Reset() {
	*x = ListUserRentalsResponse{}
	mi := &file_rental_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRentalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRentalsResponse) ProtoMessage() {}

func (x *ListUserRentalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rental_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRentalsResponse.ProtoReflect.Descriptor instead.
func (*ListUserRentalsResponse) Descriptor() ([]byte, []int) {
	return file_rental_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserRentalsResponse) GetRentals() []*Rental {
	if x != nil {
		return x.Rentals
	}
	return nil
}

var File_rental_proto protoreflect.FileDescriptor

const file_rental_proto_rawDesc = "" +
	"\n" +
	"\frental.proto\x12\x06rental\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\x06Rental\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06car_id\x18\x03 \x01(\x03R\x05carId\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x06 \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xd3\x01\n" +
	"\x0eRentCarRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x15\n" +
	"\x06car_id\x18\x02 \x01(\x03R\x05carId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x1f\n" +
	"\vdaily_price\x18\x05 \x01(\x01R\n" +
	"dailyPrice\".\n" +
	"\x0fRentCarResponse\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\x03R\brentalId\"4\n" +
	"\x15CompleteRentalRequest\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\x03R\brentalId\"2\n" +
	"\x16CompleteRentalResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x10GetRentalRequest\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\x03R\brentalId\";\n" +
	"\x11GetRentalResponse\x12&\n" +
	"\x06rental\x18\x01 \x01(\v2\x0e.rental.RentalR\x06rental\"1\n" +
	"\x16ListUserRentalsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"C\n" +
	"\x17ListUserRentalsResponse\x12(\n" +
	"\arentals\x18\x01 \x03(\v2\x0e.rental.RentalR\arentals2\xb2\x02\n" +
	"\rRentalService\x12:\n" +
	"\aRentCar\x12\x16.rental.RentCarRequest\x1a\x17.rental.RentCarResponse\x12O\n" +
	"\x0eCompleteRental\x12\x1d.rental.CompleteRentalRequest\x1a\x1e.rental.CompleteRentalResponse\x12@\n" +
	"\tGetRental\x12\x18.rental.GetRentalRequest\x1a\x19.rental.GetRentalResponse\x12R\n" +
	"\x0fListUserRentals\x12\x1e.rental.ListUserRentalsRequest\x1a\x1f.rental.ListUserRentalsResponseB'Z%\tCarRental/rental-service/proto;protob\x06proto3"

var (
	file_rental_proto_rawDescOnce sync.Once
	file_rental_proto_rawDescData []byte
)

func file_rental_proto_rawDescGZIP() []byte {
	file_rental_proto_rawDescOnce.Do(func() {
		file_rental_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rental_proto_rawDesc), len(file_rental_proto_rawDesc)))
	})
	return file_rental_proto_rawDescData
}

var file_rental_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_rental_proto_goTypes = []any{
	(*Rental)(nil),                  // 0: rental.Rental
	(*RentCarRequest)(nil),          // 1: rental.RentCarRequest
	(*RentCarResponse)(nil),         // 2: rental.RentCarResponse
	(*CompleteRentalRequest)(nil),   // 3: rental.CompleteRentalRequest
	(*CompleteRentalResponse)(nil),  // 4: rental.CompleteRentalResponse
	(*GetRentalRequest)(nil),        // 5: rental.GetRentalRequest
	(*GetRentalResponse)(nil),       // 6: rental.GetRentalResponse
	(*ListUserRentalsRequest)(nil),  // 7: rental.ListUserRentalsRequest
	(*ListUserRentalsResponse)(nil), // 8: rental.ListUserRentalsResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_rental_proto_depIdxs = []int32{
	9,  // 0: rental.Rental.start_date:type_name -> google.protobuf.Timestamp
	9,  // 1: rental.Rental.end_date:type_name -> google.protobuf.Timestamp
	9,  // 2: rental.RentCarRequest.start_date:type_name -> google.protobuf.Timestamp
	9,  // 3: rental.RentCarRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 4: rental.GetRentalResponse.rental:type_name -> rental.Rental
	0,  // 5: rental.ListUserRentalsResponse.rentals:type_name -> rental.Rental
	1,  // 6: rental.RentalService.RentCar:input_type -> rental.RentCarRequest
	3,  // 7: rental.RentalService.CompleteRental:input_type -> rental.CompleteRentalRequest
	5,  // 8: rental.RentalService.GetRental:input_type -> rental.GetRentalRequest
	7,  // 9: rental.RentalService.ListUserRentals:input_type -> rental.ListUserRentalsRequest
	2,  // 10: rental.RentalService.RentCar:output_type -> rental.RentCarResponse
	4,  // 11: rental.RentalService.CompleteRental:output_type -> rental.CompleteRentalResponse
	6,  // 12: rental.RentalService.GetRental:output_type -> rental.GetRentalResponse
	8,  // 13: rental.RentalService.ListUserRentals:output_type -> rental.ListUserRentalsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rental_proto_init() }
func file_rental_proto_init() {
	if File_rental_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rental_proto_rawDesc), len(file_rental_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rental_proto_goTypes,
		DependencyIndexes: file_rental_proto_depIdxs,
		MessageInfos:      file_rental_proto_msgTypes,
	}.Build()
	File_rental_proto = out.File
	file_rental_proto_goTypes = nil
	file_rental_proto_depIdxs = nil
}
