// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Statistics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders    int64                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalRevenue   float64                `protobuf:"fixed64,2,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageRating  float64                `protobuf:"fixed64,3,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	TotalFeedbacks int64                  `protobuf:"varint,4,opt,name=total_feedbacks,json=totalFeedbacks,proto3" json:"total_feedbacks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *Statistics) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *Statistics) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *Statistics) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *Statistics) GetTotalFeedbacks() int64 {
	if x != nil {
		return x.TotalFeedbacks
	}
	return 0
}

type GetStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsRequest) Reset() {
	*x = GetStatisticsRequest{}
	mi := &file_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsRequest) ProtoMessage() {}

func (x *GetStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{1}
}

type GetStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Statistics            `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatisticsResponse) GetStats() *Statistics {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_statistics_proto protoreflect.FileDescriptor

const file_statistics_proto_rawDesc = "" +
	"\n" +
	"\x10statistics.proto\x12\n" +
	"statistics\"\xa4\x01\n" +
	"\n" +
	"Statistics\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x03R\vtotalOrders\x12#\n" +
	"\rtotal_revenue\x18\x02 \x01(\x01R\ftotalRevenue\x12%\n" +
	"\x0eaverage_rating\x18\x03 \x01(\x01R\raverageRating\x12'\n" +
	"\x0ftotal_feedbacks\x18\x04 \x01(\x03R\x0etotalFeedbacks\"\x16\n" +
	"\x14GetStatisticsRequest\"E\n" +
	"\x15GetStatisticsResponse\x12,\n" +
	"\x05stats\x18\x01 \x01(\v2\x16.statistics.StatisticsR\x05stats2i\n" +
	"\x11StatisticsService\x12T\n" +
	"\rGetStatistics\x12 .statistics.GetStatisticsRequest\x1a!.statistics.GetStatisticsResponseB*Z(CarRental/statistics-service/proto;protob\x06proto3"

var (
	file_statistics_proto_rawDescOnce sync.Once
	file_statistics_proto_rawDescData []byte
)

func file_statistics_proto_rawDescGZIP() []byte {
	file_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)))
	})
	return file_statistics_proto_rawDescData
}

var file_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_statistics_proto_goTypes = []any{
	(*Statistics)(nil),            // 0: statistics.Statistics
	(*GetStatisticsRequest)(nil),  // 1: statistics.GetStatisticsRequest
	(*GetStatisticsResponse)(nil), // 2: statistics.GetStatisticsResponse
}
var file_statistics_proto_depIdxs = []int32{
	0, // 0: statistics.GetStatisticsResponse.stats:type_name -> statistics.Statistics
	1, // 1: statistics.StatisticsService.GetStatistics:input_type -> statistics.GetStatisticsRequest
	2, // 2: statistics.StatisticsService.GetStatistics:output_type -> statistics.GetStatisticsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_statistics_proto_init() }
func file_statistics_proto_init() {
	if File_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_proto_rawDesc), len(file_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_proto_msgTypes,
	}.Build()
	File_statistics_proto = out.File
	file_statistics_proto_goTypes = nil
	file_statistics_proto_depIdxs = nil
}
