// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: notification-service/proto/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *EmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type EmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailResponse) Reset() {
	*x = EmailResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailResponse) ProtoMessage() {}

func (x *EmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailResponse.ProtoReflect.Descriptor instead.
func (*EmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *EmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notification_service_proto_notification_proto protoreflect.FileDescriptor

const file_notification_service_proto_notification_proto_rawDesc = "" +
	"\n" +
	"-notification-service/proto/notification.proto\x12\fnotification\"L\n" +
	"\fEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\")\n" +
	"\rEmailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2[\n" +
	"\x13NotificationService\x12D\n" +
	"\tSendEmail\x12\x1a.notification.EmailRequest\x1a\x1b.notification.EmailResponseB+Z)notification-service/proto;notificationpbb\x06proto3"

var (
	file_notification_service_proto_notification_proto_rawDescOnce sync.Once
	file_notification_service_proto_notification_proto_rawDescData []byte
)

func file_notification_service_proto_notification_proto_rawDescGZIP() []byte {
	file_notification_service_proto_notification_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_notification_proto_rawDesc), len(file_notification_service_proto_notification_proto_rawDesc)))
	})
	return file_notification_service_proto_notification_proto_rawDescData
}

var file_notification_service_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_service_proto_notification_proto_goTypes = []any{
	(*EmailRequest)(nil),  // 0: notification.EmailRequest
	(*EmailResponse)(nil), // 1: notification.EmailResponse
}
var file_notification_service_proto_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.SendEmail:input_type -> notification.EmailRequest
	1, // 1: notification.NotificationService.SendEmail:output_type -> notification.EmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_service_proto_notification_proto_init() }
func file_notification_service_proto_notification_proto_init() {
	if File_notification_service_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_notification_proto_rawDesc), len(file_notification_service_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_service_proto_notification_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_notification_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_notification_proto_msgTypes,
	}.Build()
	File_notification_service_proto_notification_proto = out.File
	file_notification_service_proto_notification_proto_goTypes = nil
	file_notification_service_proto_notification_proto_depIdxs = nil
}
