// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: car.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_car_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{0}
}

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Fuel          string                 `protobuf:"bytes,4,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Transmission  string                 `protobuf:"bytes,5,opt,name=transmission,proto3" json:"transmission,omitempty"`
	PricePerDay   float32                `protobuf:"fixed32,6,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_car_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{1}
}

func (x *Car) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetFuel() string {
	if x != nil {
		return x.Fuel
	}
	return ""
}

func (x *Car) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *Car) GetPricePerDay() float32 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

type CreateCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Fuel          string                 `protobuf:"bytes,3,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Transmission  string                 `protobuf:"bytes,4,opt,name=transmission,proto3" json:"transmission,omitempty"`
	PricePerDay   float32                `protobuf:"fixed32,5,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCarRequest) Reset() {
	*x = CreateCarRequest{}
	mi := &file_car_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarRequest) ProtoMessage() {}

func (x *CreateCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarRequest.ProtoReflect.Descriptor instead.
func (*CreateCarRequest) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCarRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateCarRequest) GetFuel() string {
	if x != nil {
		return x.Fuel
	}
	return ""
}

func (x *CreateCarRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *CreateCarRequest) GetPricePerDay() float32 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

type GetCarByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCarByIDRequest) Reset() {
	*x = GetCarByIDRequest{}
	mi := &file_car_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCarByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarByIDRequest) ProtoMessage() {}

func (x *GetCarByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarByIDRequest.ProtoReflect.Descriptor instead.
func (*GetCarByIDRequest) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{3}
}

func (x *GetCarByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Fuel          string                 `protobuf:"bytes,4,opt,name=fuel,proto3" json:"fuel,omitempty"`
	Transmission  string                 `protobuf:"bytes,5,opt,name=transmission,proto3" json:"transmission,omitempty"`
	PricePerDay   float32                `protobuf:"fixed32,6,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCarRequest) Reset() {
	*x = UpdateCarRequest{}
	mi := &file_car_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarRequest) ProtoMessage() {}

func (x *UpdateCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarRequest) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCarRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCarRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateCarRequest) GetFuel() string {
	if x != nil {
		return x.Fuel
	}
	return ""
}

func (x *UpdateCarRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *UpdateCarRequest) GetPricePerDay() float32 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

type DeleteCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCarRequest) Reset() {
	*x = DeleteCarRequest{}
	mi := &file_car_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarRequest) ProtoMessage() {}

func (x *DeleteCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarRequest.ProtoReflect.Descriptor instead.
func (*DeleteCarRequest) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCarRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Car           *Car                   `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarResponse) Reset() {
	*x = CarResponse{}
	mi := &file_car_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarResponse) ProtoMessage() {}

func (x *CarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarResponse.ProtoReflect.Descriptor instead.
func (*CarResponse) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{6}
}

func (x *CarResponse) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

type CarListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarListResponse) Reset() {
	*x = CarListResponse{}
	mi := &file_car_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarListResponse) ProtoMessage() {}

func (x *CarListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarListResponse.ProtoReflect.Descriptor instead.
func (*CarListResponse) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{7}
}

func (x *CarListResponse) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_car_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_car_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_car_proto protoreflect.FileDescriptor

const file_car_proto_rawDesc = "" +
	"\n" +
	"\tcar.proto\x12\x03car\"\a\n" +
	"\x05Empty\"\x9d\x01\n" +
	"\x03Car\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04fuel\x18\x04 \x01(\tR\x04fuel\x12\"\n" +
	"\ftransmission\x18\x05 \x01(\tR\ftransmission\x12\"\n" +
	"\rprice_per_day\x18\x06 \x01(\x02R\vpricePerDay\"\x9a\x01\n" +
	"\x10CreateCarRequest\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04fuel\x18\x03 \x01(\tR\x04fuel\x12\"\n" +
	"\ftransmission\x18\x04 \x01(\tR\ftransmission\x12\"\n" +
	"\rprice_per_day\x18\x05 \x01(\x02R\vpricePerDay\"#\n" +
	"\x11GetCarByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xaa\x01\n" +
	"\x10UpdateCarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04fuel\x18\x04 \x01(\tR\x04fuel\x12\"\n" +
	"\ftransmission\x18\x05 \x01(\tR\ftransmission\x12\"\n" +
	"\rprice_per_day\x18\x06 \x01(\x02R\vpricePerDay\"\"\n" +
	"\x10DeleteCarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\vCarResponse\x12\x1a\n" +
	"\x03car\x18\x01 \x01(\v2\b.car.CarR\x03car\"/\n" +
	"\x0fCarListResponse\x12\x1c\n" +
	"\x04cars\x18\x01 \x03(\v2\b.car.CarR\x04cars\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x97\x02\n" +
	"\n" +
	"CarService\x124\n" +
	"\tCreateCar\x12\x15.car.CreateCarRequest\x1a\x10.car.CarResponse\x126\n" +
	"\n" +
	"GetCarByID\x12\x16.car.GetCarByIDRequest\x1a\x10.car.CarResponse\x12,\n" +
	"\bListCars\x12\n" +
	".car.Empty\x1a\x14.car.CarListResponse\x124\n" +
	"\tUpdateCar\x12\x15.car.UpdateCarRequest\x1a\x10.car.CarResponse\x127\n" +
	"\tDeleteCar\x12\x15.car.DeleteCarRequest\x1a\x13.car.DeleteResponseB#Z!CarRental/car-service/proto;protob\x06proto3"

var (
	file_car_proto_rawDescOnce sync.Once
	file_car_proto_rawDescData []byte
)

func file_car_proto_rawDescGZIP() []byte {
	file_car_proto_rawDescOnce.Do(func() {
		file_car_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)))
	})
	return file_car_proto_rawDescData
}

var file_car_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_car_proto_goTypes = []any{
	(*Empty)(nil),             // 0: car.Empty
	(*Car)(nil),               // 1: car.Car
	(*CreateCarRequest)(nil),  // 2: car.CreateCarRequest
	(*GetCarByIDRequest)(nil), // 3: car.GetCarByIDRequest
	(*UpdateCarRequest)(nil),  // 4: car.UpdateCarRequest
	(*DeleteCarRequest)(nil),  // 5: car.DeleteCarRequest
	(*CarResponse)(nil),       // 6: car.CarResponse
	(*CarListResponse)(nil),   // 7: car.CarListResponse
	(*DeleteResponse)(nil),    // 8: car.DeleteResponse
}
var file_car_proto_depIdxs = []int32{
	1, // 0: car.CarResponse.car:type_name -> car.Car
	1, // 1: car.CarListResponse.cars:type_name -> car.Car
	2, // 2: car.CarService.CreateCar:input_type -> car.CreateCarRequest
	3, // 3: car.CarService.GetCarByID:input_type -> car.GetCarByIDRequest
	0, // 4: car.CarService.ListCars:input_type -> car.Empty
	4, // 5: car.CarService.UpdateCar:input_type -> car.UpdateCarRequest
	5, // 6: car.CarService.DeleteCar:input_type -> car.DeleteCarRequest
	6, // 7: car.CarService.CreateCar:output_type -> car.CarResponse
	6, // 8: car.CarService.GetCarByID:output_type -> car.CarResponse
	7, // 9: car.CarService.ListCars:output_type -> car.CarListResponse
	6, // 10: car.CarService.UpdateCar:output_type -> car.CarResponse
	8, // 11: car.CarService.DeleteCar:output_type -> car.DeleteResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_car_proto_init() }
func file_car_proto_init() {
	if File_car_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_car_proto_rawDesc), len(file_car_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_car_proto_goTypes,
		DependencyIndexes: file_car_proto_depIdxs,
		MessageInfos:      file_car_proto_msgTypes,
	}.Build()
	File_car_proto = out.File
	file_car_proto_goTypes = nil
	file_car_proto_depIdxs = nil
}
