// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: feedback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RentalId      int64                  `protobuf:"varint,2,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Feedback) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

func (x *Feedback) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Feedback) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Feedback) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Feedback) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubmitFeedbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      int64                  `protobuf:"varint,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackRequest) Reset() {
	*x = SubmitFeedbackRequest{}
	mi := &file_feedback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackRequest) ProtoMessage() {}

func (x *SubmitFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackRequest.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitFeedbackRequest) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

func (x *SubmitFeedbackRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitFeedbackRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *SubmitFeedbackRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type SubmitFeedbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    int64                  `protobuf:"varint,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitFeedbackResponse) Reset() {
	*x = SubmitFeedbackResponse{}
	mi := &file_feedback_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitFeedbackResponse) ProtoMessage() {}

func (x *SubmitFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitFeedbackResponse.ProtoReflect.Descriptor instead.
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitFeedbackResponse) GetFeedbackId() int64 {
	if x != nil {
		return x.FeedbackId
	}
	return 0
}

type GetFeedbackByRentalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RentalId      int64                  `protobuf:"varint,1,opt,name=rental_id,json=rentalId,proto3" json:"rental_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByRentalRequest) Reset() {
	*x = GetFeedbackByRentalRequest{}
	mi := &file_feedback_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByRentalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByRentalRequest) ProtoMessage() {}

func (x *GetFeedbackByRentalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByRentalRequest.ProtoReflect.Descriptor instead.
func (*GetFeedbackByRentalRequest) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{3}
}

func (x *GetFeedbackByRentalRequest) GetRentalId() int64 {
	if x != nil {
		return x.RentalId
	}
	return 0
}

type GetFeedbackByRentalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feedbacks     []*Feedback            `protobuf:"bytes,1,rep,name=feedbacks,proto3" json:"feedbacks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedbackByRentalResponse) Reset() {
	*x = GetFeedbackByRentalResponse{}
	mi := &file_feedback_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedbackByRentalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedbackByRentalResponse) ProtoMessage() {}

func (x *GetFeedbackByRentalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedbackByRentalResponse.ProtoReflect.Descriptor instead.
func (*GetFeedbackByRentalResponse) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{4}
}

func (x *GetFeedbackByRentalResponse) GetFeedbacks() []*Feedback {
	if x != nil {
		return x.Feedbacks
	}
	return nil
}

var File_feedback_proto protoreflect.FileDescriptor

const file_feedback_proto_rawDesc = "" +
	"\n" +
	"\x0efeedback.proto\x12\bfeedback\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\x01\n" +
	"\bFeedback\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trental_id\x18\x02 \x01(\x03R\brentalId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x7f\n" +
	"\x15SubmitFeedbackRequest\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\x03R\brentalId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x04 \x01(\tR\acomment\"9\n" +
	"\x16SubmitFeedbackResponse\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\x03R\n" +
	"feedbackId\"9\n" +
	"\x1aGetFeedbackByRentalRequest\x12\x1b\n" +
	"\trental_id\x18\x01 \x01(\x03R\brentalId\"O\n" +
	"\x1bGetFeedbackByRentalResponse\x120\n" +
	"\tfeedbacks\x18\x01 \x03(\v2\x12.feedback.FeedbackR\tfeedbacks2\xca\x01\n" +
	"\x0fFeedbackService\x12S\n" +
	"\x0eSubmitFeedback\x12\x1f.feedback.SubmitFeedbackRequest\x1a .feedback.SubmitFeedbackResponse\x12b\n" +
	"\x13GetFeedbackByRental\x12$.feedback.GetFeedbackByRentalRequest\x1a%.feedback.GetFeedbackByRentalResponseB)Z'\tCarRental/feedback-service/proto;protob\x06proto3"

var (
	file_feedback_proto_rawDescOnce sync.Once
	file_feedback_proto_rawDescData []byte
)

func file_feedback_proto_rawDescGZIP() []byte {
	file_feedback_proto_rawDescOnce.Do(func() {
		file_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)))
	})
	return file_feedback_proto_rawDescData
}

var file_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_feedback_proto_goTypes = []any{
	(*Feedback)(nil),                    // 0: feedback.Feedback
	(*SubmitFeedbackRequest)(nil),       // 1: feedback.SubmitFeedbackRequest
	(*SubmitFeedbackResponse)(nil),      // 2: feedback.SubmitFeedbackResponse
	(*GetFeedbackByRentalRequest)(nil),  // 3: feedback.GetFeedbackByRentalRequest
	(*GetFeedbackByRentalResponse)(nil), // 4: feedback.GetFeedbackByRentalResponse
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_feedback_proto_depIdxs = []int32{
	5, // 0: feedback.Feedback.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: feedback.GetFeedbackByRentalResponse.feedbacks:type_name -> feedback.Feedback
	1, // 2: feedback.FeedbackService.SubmitFeedback:input_type -> feedback.SubmitFeedbackRequest
	3, // 3: feedback.FeedbackService.GetFeedbackByRental:input_type -> feedback.GetFeedbackByRentalRequest
	2, // 4: feedback.FeedbackService.SubmitFeedback:output_type -> feedback.SubmitFeedbackResponse
	4, // 5: feedback.FeedbackService.GetFeedbackByRental:output_type -> feedback.GetFeedbackByRentalResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_feedback_proto_init() }
func file_feedback_proto_init() {
	if File_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feedback_proto_goTypes,
		DependencyIndexes: file_feedback_proto_depIdxs,
		MessageInfos:      file_feedback_proto_msgTypes,
	}.Build()
	File_feedback_proto = out.File
	file_feedback_proto_goTypes = nil
	file_feedback_proto_depIdxs = nil
}
